publish:
  whoami: asf-site

github:
  description: "Website sources for the Apache Directory website"
  homepage: https://directory.apache.org/
  labels:
    - apache
    - directory
    - hugo
  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
